# =============================================================================
# Cloud Build Configuration for Production Deployment
# =============================================================================
# This configuration:
# 1. Builds the Docker image
# 2. Pushes to Artifact Registry
# 3. Deploys to Cloud Run across multiple regions (blue-green)
# 4. Validates the deployment
# =============================================================================

timeout: 1800s # 30 minutes

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _PROJECT_ID: ''
  _REGION: 'europe-west1'
  _ARTIFACT_REGISTRY: ''
  _APP_NAME: 'what-time-is-it'
  _CLOUD_RUN_REGIONS: 'europe-west1,europe-west4,us-central1'
  _ENVIRONMENT: 'prod'
  _CANARY_PERCENT: '10'
  _SERVICE_ACCOUNT: ''

steps:
  # ==========================================================================
  # Step 1: Build the Docker image
  # ==========================================================================
  - id: 'build-image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --tag "${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}" \
          --tag "${_ARTIFACT_REGISTRY}/${_APP_NAME}:${COMMIT_SHA}" \
          --tag "${_ARTIFACT_REGISTRY}/${_APP_NAME}:latest" \
          --cache-from "${_ARTIFACT_REGISTRY}/${_APP_NAME}:latest" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          .
    env:
      - 'DOCKER_BUILDKIT=1'

  # ==========================================================================
  # Step 2: Push the Docker image to Artifact Registry
  # ==========================================================================
  - id: 'push-image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push "${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}"
        docker push "${_ARTIFACT_REGISTRY}/${_APP_NAME}:${COMMIT_SHA}"
        docker push "${_ARTIFACT_REGISTRY}/${_APP_NAME}:latest"
    waitFor: ['build-image']

  # ==========================================================================
  # Step 3: Scan the image for vulnerabilities
  # ==========================================================================
  - id: 'scan-image'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Scanning image for vulnerabilities..."
        gcloud artifacts docker images scan \
          "${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}" \
          --project="${_PROJECT_ID}" \
          --format="json" > /workspace/scan_results.json || true
        
        # Check for critical vulnerabilities
        CRITICAL=$$(cat /workspace/scan_results.json | jq '.response.scan.vulnerabilities.critical // 0')
        if [ "$$CRITICAL" -gt 0 ]; then
          echo "WARNING: Found $$CRITICAL critical vulnerabilities"
          # Uncomment the next line to fail the build on critical vulnerabilities
          # exit 1
        fi
        
        echo "Vulnerability scan completed"
    waitFor: ['push-image']

  # ==========================================================================
  # Step 4: Deploy to first region with canary traffic
  # ==========================================================================
  - id: 'deploy-canary'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the first region for canary deployment
        FIRST_REGION=$$(echo "${_CLOUD_RUN_REGIONS}" | cut -d',' -f1)
        SERVICE_NAME="${_APP_NAME}-${_ENVIRONMENT}-$${FIRST_REGION}"
        
        echo "Deploying canary to $${FIRST_REGION}..."
        
        # Deploy new revision with no traffic
        gcloud run deploy $${SERVICE_NAME} \
          --project="${_PROJECT_ID}" \
          --region="$${FIRST_REGION}" \
          --image="${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}" \
          --no-traffic \
          --tag="canary-${SHORT_SHA}" \
          --quiet
        
        # If canary percent is > 0, route some traffic to the new revision
        if [ "${_CANARY_PERCENT}" -gt 0 ]; then
          echo "Routing ${_CANARY_PERCENT}% traffic to canary..."
          
          # Get the new revision name
          NEW_REVISION=$$(gcloud run revisions list \
            --service="$${SERVICE_NAME}" \
            --region="$${FIRST_REGION}" \
            --project="${_PROJECT_ID}" \
            --format="value(REVISION)" \
            --limit=1)
          
          # Update traffic split
          gcloud run services update-traffic $${SERVICE_NAME} \
            --project="${_PROJECT_ID}" \
            --region="$${FIRST_REGION}" \
            --to-revisions="$${NEW_REVISION}=${_CANARY_PERCENT}" \
            --quiet
        fi
        
        echo "Canary deployment complete for $${FIRST_REGION}"
    waitFor: ['scan-image']

  # ==========================================================================
  # Step 5: Validate canary deployment
  # ==========================================================================
  - id: 'validate-canary'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        FIRST_REGION=$$(echo "${_CLOUD_RUN_REGIONS}" | cut -d',' -f1)
        SERVICE_NAME="${_APP_NAME}-${_ENVIRONMENT}-$${FIRST_REGION}"
        
        echo "Validating canary deployment..."
        
        # Get the canary URL
        CANARY_URL=$$(gcloud run services describe $${SERVICE_NAME} \
          --project="${_PROJECT_ID}" \
          --region="$${FIRST_REGION}" \
          --format="value(status.url)")
        
        echo "Testing canary at: $${CANARY_URL}"
        
        # Wait for the service to be ready
        sleep 10
        
        # Perform health check
        HTTP_CODE=$$(curl -s -o /dev/null -w "%{http_code}" "$${CANARY_URL}" -H "Host: $${CANARY_URL#https://}")
        
        if [ "$$HTTP_CODE" -eq 200 ]; then
          echo "Canary validation successful (HTTP $$HTTP_CODE)"
        else
          echo "Canary validation failed (HTTP $$HTTP_CODE)"
          exit 1
        fi
    waitFor: ['deploy-canary']

  # ==========================================================================
  # Step 6: Deploy to all regions with full traffic
  # ==========================================================================
  - id: 'deploy-all-regions'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to all regions with full traffic..."
        
        # Convert comma-separated regions to array
        IFS=',' read -ra REGIONS <<< "${_CLOUD_RUN_REGIONS}"
        
        for REGION in "$${REGIONS[@]}"; do
          SERVICE_NAME="${_APP_NAME}-${_ENVIRONMENT}-$${REGION}"
          
          echo "Deploying to $${REGION}..."
          
          # Deploy with full traffic
          gcloud run deploy $${SERVICE_NAME} \
            --project="${_PROJECT_ID}" \
            --region="$${REGION}" \
            --image="${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}" \
            --quiet
          
          echo "Deployment complete for $${REGION}"
        done
        
        echo "All regions deployed successfully"
    waitFor: ['validate-canary']

  # ==========================================================================
  # Step 7: Final validation across all regions
  # ==========================================================================
  - id: 'validate-all-regions'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Validating deployment across all regions..."
        
        IFS=',' read -ra REGIONS <<< "${_CLOUD_RUN_REGIONS}"
        ALL_HEALTHY=true
        
        for REGION in "$${REGIONS[@]}"; do
          SERVICE_NAME="${_APP_NAME}-${_ENVIRONMENT}-$${REGION}"
          
          SERVICE_URL=$$(gcloud run services describe $${SERVICE_NAME} \
            --project="${_PROJECT_ID}" \
            --region="$${REGION}" \
            --format="value(status.url)")
          
          HTTP_CODE=$$(curl -s -o /dev/null -w "%{http_code}" "$${SERVICE_URL}" -H "Host: $${SERVICE_URL#https://}")
          
          if [ "$$HTTP_CODE" -eq 200 ]; then
            echo "✓ $${REGION}: Healthy (HTTP $$HTTP_CODE)"
          else
            echo "✗ $${REGION}: Unhealthy (HTTP $$HTTP_CODE)"
            ALL_HEALTHY=false
          fi
        done
        
        if [ "$$ALL_HEALTHY" = true ]; then
          echo "All regions validated successfully"
        else
          echo "Some regions failed validation"
          exit 1
        fi
    waitFor: ['deploy-all-regions']

  # ==========================================================================
  # Step 8: Tag the successful deployment
  # ==========================================================================
  - id: 'tag-release'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Tag the successful image with a timestamp
        TIMESTAMP=$$(date +%Y%m%d-%H%M%S)
        docker pull "${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}"
        docker tag "${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}" \
          "${_ARTIFACT_REGISTRY}/${_APP_NAME}:release-$${TIMESTAMP}"
        docker push "${_ARTIFACT_REGISTRY}/${_APP_NAME}:release-$${TIMESTAMP}"
        
        echo "Tagged release as: release-$${TIMESTAMP}"
    waitFor: ['validate-all-regions']

# =============================================================================
# Images to push to Artifact Registry
# =============================================================================
images:
  - '${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}'
  - '${_ARTIFACT_REGISTRY}/${_APP_NAME}:${COMMIT_SHA}'
  - '${_ARTIFACT_REGISTRY}/${_APP_NAME}:latest'
