# =============================================================================
# Cloud Build Configuration for Production Deployment
# =============================================================================
# This configuration:
# 1. Builds the Docker image
# 2. Pushes to Artifact Registry
# 3. Deploys to Cloud Run across multiple regions (blue-green)
# 4. Validates the deployment
# =============================================================================

timeout: 1800s # 30 minutes

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _PROJECT_ID: ''
  _REGION: 'europe-west1'
  _ARTIFACT_REGISTRY: ''
  _APP_NAME: 'what-time-is-it'
  _CLOUD_RUN_REGIONS: 'europe-west1,europe-west4,us-central1'
  _ENVIRONMENT: 'prod'
  _CANARY_PERCENT: '10'
  _SERVICE_ACCOUNT: ''

# Secret Manager secrets for Docker Hub authentication
availableSecrets:
  secretManager:
    - versionName: projects/${_PROJECT_ID}/secrets/dockerhub-username/versions/latest
      env: 'DOCKERHUB_USERNAME'
    - versionName: projects/${_PROJECT_ID}/secrets/dockerhub-token/versions/latest
      env: 'DOCKERHUB_TOKEN'

steps:
  # ==========================================================================
  # Step 0: Authenticate with Docker Hub
  # ==========================================================================
  - id: 'docker-login'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$DOCKERHUB_TOKEN" | docker login -u "$$DOCKERHUB_USERNAME" --password-stdin
    secretEnv:
      - 'DOCKERHUB_USERNAME'
      - 'DOCKERHUB_TOKEN'

  # ==========================================================================
  # Step 1: Build the Docker image
  # ==========================================================================
  - id: 'build-image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --tag "${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}" \
          --tag "${_ARTIFACT_REGISTRY}/${_APP_NAME}:${COMMIT_SHA}" \
          --tag "${_ARTIFACT_REGISTRY}/${_APP_NAME}:latest" \
          --cache-from "${_ARTIFACT_REGISTRY}/${_APP_NAME}:latest" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          .
    env:
      - 'DOCKER_BUILDKIT=1'
    waitFor: ['docker-login']

  # ==========================================================================
  # Step 2: Push the Docker image to Artifact Registry
  # ==========================================================================
  - id: 'push-image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push "${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}"
        docker push "${_ARTIFACT_REGISTRY}/${_APP_NAME}:${COMMIT_SHA}"
        docker push "${_ARTIFACT_REGISTRY}/${_APP_NAME}:latest"
    waitFor: ['build-image']

  # ==========================================================================
  # Step 3: Scan the image for vulnerabilities
  # ==========================================================================
  - id: 'scan-image'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Scanning image for vulnerabilities..."
        
        # Run the scan and capture the operation name
        SCAN_OUTPUT=$$(gcloud artifacts docker images scan \
          "${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}" \
          --project="${_PROJECT_ID}" \
          --format="value(response.scan)" 2>&1) || {
          echo "Warning: Vulnerability scan failed or not available, continuing..."
          echo "Vulnerability scan completed (skipped)"
          exit 0
        }
        
        if [ -n "$${SCAN_OUTPUT}" ]; then
          echo "Scan completed: $${SCAN_OUTPUT}"
          
          # List vulnerabilities if scan was successful
          gcloud artifacts docker images list-vulnerabilities "$${SCAN_OUTPUT}" \
            --project="${_PROJECT_ID}" \
            --format="table(vulnerability.effectiveSeverity, vulnerability.cvssScore, vulnerability.packageIssue.affectedPackage)" \
            2>/dev/null || echo "Could not retrieve vulnerability details"
        fi
        
        echo "Vulnerability scan completed"
    waitFor: ['push-image']

  # ==========================================================================
  # Step 4: Deploy to first region with canary traffic
  # ==========================================================================
  - id: 'deploy-canary'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the first region for canary deployment
        FIRST_REGION=$$(echo "${_CLOUD_RUN_REGIONS}" | cut -d',' -f1)
        SERVICE_NAME="${_APP_NAME}-${_ENVIRONMENT}-$${FIRST_REGION}"
        
        # Use short tag to stay under 46 char limit (service name + tag combined)
        # SHORT_SHA is 7 chars, so "c-" + 7 = 9 chars for tag
        CANARY_TAG="c-${SHORT_SHA}"
        
        echo "Deploying canary to $${FIRST_REGION} with tag $${CANARY_TAG}..."
        
        # Deploy new revision with no traffic
        gcloud run deploy $${SERVICE_NAME} \
          --project="${_PROJECT_ID}" \
          --region="$${FIRST_REGION}" \
          --image="${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}" \
          --no-traffic \
          --tag="$${CANARY_TAG}" \
          --quiet
        
        # Save the canary tag for subsequent steps
        echo "$${CANARY_TAG}" > /workspace/canary_tag.txt
        
        # If canary percent is > 0, route some traffic to the new revision
        if [ "${_CANARY_PERCENT}" -gt 0 ]; then
          echo "Routing ${_CANARY_PERCENT}% traffic to canary..."
          
          # Get the new revision name
          NEW_REVISION=$$(gcloud run revisions list \
            --service="$${SERVICE_NAME}" \
            --region="$${FIRST_REGION}" \
            --project="${_PROJECT_ID}" \
            --format="value(REVISION)" \
            --limit=1)
          
          # Update traffic split
          gcloud run services update-traffic $${SERVICE_NAME} \
            --project="${_PROJECT_ID}" \
            --region="$${FIRST_REGION}" \
            --to-revisions="$${NEW_REVISION}=${_CANARY_PERCENT}" \
            --quiet
        fi
        
        echo "Canary deployment complete for $${FIRST_REGION}"
    waitFor: ['scan-image']

  # ==========================================================================
  # Step 5: Validate canary deployment
  # ==========================================================================
  - id: 'validate-canary'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        FIRST_REGION=$$(echo "${_CLOUD_RUN_REGIONS}" | cut -d',' -f1)
        SERVICE_NAME="${_APP_NAME}-${_ENVIRONMENT}-$${FIRST_REGION}"
        CANARY_TAG=$$(cat /workspace/canary_tag.txt)
        
        echo "Validating canary deployment..."
        
        # Get the canary-specific tagged URL using gcloud native formatting
        # (avoiding jq dependency which isn't available in the gcloud image)
        CANARY_URL=$$(gcloud run services describe $${SERVICE_NAME} \
          --project="${_PROJECT_ID}" \
          --region="$${FIRST_REGION}" \
          --format="csv[no-heading](status.traffic.tag,status.traffic.url)" | \
          grep "^$${CANARY_TAG}," | cut -d',' -f2)
        
        # Fallback to main URL if tagged URL not found
        if [ -z "$${CANARY_URL}" ]; then
          echo "Warning: Could not find tagged URL, using main service URL"
          CANARY_URL=$$(gcloud run services describe $${SERVICE_NAME} \
            --project="${_PROJECT_ID}" \
            --region="$${FIRST_REGION}" \
            --format="value(status.url)")
        fi
        
        echo "Testing canary at: $${CANARY_URL}"
        
        # Wait for the service to be ready
        sleep 15
        
        # Perform health check with retries on valid endpoints
        # (root path returns 404, use /amsterdam or /london instead)
        HEALTH_ENDPOINTS="/amsterdam /london"
        MAX_RETRIES=3
        
        for ENDPOINT in $$HEALTH_ENDPOINTS; do
          RETRY_COUNT=0
          HTTP_CODE=0
          
          echo "Testing endpoint: $${CANARY_URL}$${ENDPOINT}"
          
          while [ $$RETRY_COUNT -lt $$MAX_RETRIES ]; do
            HTTP_CODE=$$(curl -s -o /dev/null -w "%{http_code}" "$${CANARY_URL}$${ENDPOINT}" --max-time 30)
            
            if [ "$$HTTP_CODE" -eq 200 ]; then
              echo "Canary validation successful for $${ENDPOINT} (HTTP $$HTTP_CODE)"
              exit 0
            fi
            
            RETRY_COUNT=$$((RETRY_COUNT + 1))
            echo "Attempt $$RETRY_COUNT for $${ENDPOINT} failed (HTTP $$HTTP_CODE), retrying in 10s..."
            sleep 10
          done
        done
        
        echo "Canary validation failed for all endpoints after $$MAX_RETRIES attempts (HTTP $$HTTP_CODE)"
        exit 1
    waitFor: ['deploy-canary']

  # ==========================================================================
  # Step 6: Deploy to all regions with full traffic
  # ==========================================================================
  - id: 'deploy-all-regions'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to all regions with full traffic..."
        
        # Convert comma-separated regions to array
        IFS=',' read -ra REGIONS <<< "${_CLOUD_RUN_REGIONS}"
        
        for REGION in "$${REGIONS[@]}"; do
          SERVICE_NAME="${_APP_NAME}-${_ENVIRONMENT}-$${REGION}"
          
          echo "Deploying to $${REGION}..."
          
          # Deploy with full traffic
          gcloud run deploy $${SERVICE_NAME} \
            --project="${_PROJECT_ID}" \
            --region="$${REGION}" \
            --image="${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}" \
            --quiet
          
          echo "Deployment complete for $${REGION}"
        done
        
        echo "All regions deployed successfully"
    waitFor: ['validate-canary']

  # ==========================================================================
  # Step 7: Final validation across all regions
  # ==========================================================================
  - id: 'validate-all-regions'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Validating deployment across all regions..."
        
        IFS=',' read -ra REGIONS <<< "${_CLOUD_RUN_REGIONS}"
        ALL_HEALTHY=true
        
        # Use valid endpoint for health check (root returns 404)
        HEALTH_ENDPOINT="/amsterdam"
        
        for REGION in "$${REGIONS[@]}"; do
          SERVICE_NAME="${_APP_NAME}-${_ENVIRONMENT}-$${REGION}"
          
          SERVICE_URL=$$(gcloud run services describe $${SERVICE_NAME} \
            --project="${_PROJECT_ID}" \
            --region="$${REGION}" \
            --format="value(status.url)")
          
          HTTP_CODE=$$(curl -s -o /dev/null -w "%{http_code}" "$${SERVICE_URL}$${HEALTH_ENDPOINT}" --max-time 30)
          
          if [ "$$HTTP_CODE" -eq 200 ]; then
            echo "✓ $${REGION}: Healthy (HTTP $$HTTP_CODE)"
          else
            echo "✗ $${REGION}: Unhealthy (HTTP $$HTTP_CODE)"
            ALL_HEALTHY=false
          fi
        done
        
        if [ "$$ALL_HEALTHY" = true ]; then
          echo "All regions validated successfully"
        else
          echo "Some regions failed validation"
          exit 1
        fi
    waitFor: ['deploy-all-regions']

  # ==========================================================================
  # Step 8: Tag the successful deployment
  # ==========================================================================
  - id: 'tag-release'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Tag the successful image with a timestamp
        TIMESTAMP=$$(date +%Y%m%d-%H%M%S)
        docker pull "${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}"
        docker tag "${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}" \
          "${_ARTIFACT_REGISTRY}/${_APP_NAME}:release-$${TIMESTAMP}"
        docker push "${_ARTIFACT_REGISTRY}/${_APP_NAME}:release-$${TIMESTAMP}"
        
        echo "Tagged release as: release-$${TIMESTAMP}"
    waitFor: ['validate-all-regions']

# =============================================================================
# Images to push to Artifact Registry
# =============================================================================
images:
  - '${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}'
  - '${_ARTIFACT_REGISTRY}/${_APP_NAME}:${COMMIT_SHA}'
  - '${_ARTIFACT_REGISTRY}/${_APP_NAME}:latest'
